// <auto-generated />
using System;
using LocalizationProvider.PostgreSql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LocalizationProvider.PostgreSql.Migrations
{
    [DbContext(typeof(ResourceDbContext))]
    [Migration("20230702185605_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LocalizationProvider.PostgreSql.Models.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvailableCultures")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefaultCulture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("LocalizationProvider.PostgreSql.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Culture", "ResourceId")
                        .IsUnique();

                    b.ToTable("Images");
                });

            modelBuilder.Entity("LocalizationProvider.PostgreSql.Models.List", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Culture", "ResourceId")
                        .IsUnique();

                    b.ToTable("Lists");
                });

            modelBuilder.Entity("LocalizationProvider.PostgreSql.Models.ListOption", b =>
                {
                    b.Property<int>("ListId")
                        .HasColumnType("integer");

                    b.Property<int>("OptionId")
                        .HasColumnType("integer");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.HasKey("ListId", "OptionId");

                    b.HasIndex("OptionId");

                    b.HasIndex("ListId", "Index")
                        .IsUnique();

                    b.ToTable("ListOptions");
                });

            modelBuilder.Entity("LocalizationProvider.PostgreSql.Models.Text", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Culture", "ResourceId")
                        .IsUnique();

                    b.ToTable("Texts");
                });

            modelBuilder.Entity("LocalizationProvider.PostgreSql.Models.Image", b =>
                {
                    b.HasOne("LocalizationProvider.PostgreSql.Models.Application", "Application")
                        .WithMany("Images")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("LocalizationProvider.PostgreSql.Models.List", b =>
                {
                    b.HasOne("LocalizationProvider.PostgreSql.Models.Application", "Application")
                        .WithMany("Lists")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("LocalizationProvider.PostgreSql.Models.ListOption", b =>
                {
                    b.HasOne("LocalizationProvider.PostgreSql.Models.List", "List")
                        .WithMany("ListOptions")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocalizationProvider.PostgreSql.Models.Text", "Option")
                        .WithMany("OptionList")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("List");

                    b.Navigation("Option");
                });

            modelBuilder.Entity("LocalizationProvider.PostgreSql.Models.Text", b =>
                {
                    b.HasOne("LocalizationProvider.PostgreSql.Models.Application", "Application")
                        .WithMany("Texts")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("LocalizationProvider.PostgreSql.Models.Application", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Lists");

                    b.Navigation("Texts");
                });

            modelBuilder.Entity("LocalizationProvider.PostgreSql.Models.List", b =>
                {
                    b.Navigation("ListOptions");
                });

            modelBuilder.Entity("LocalizationProvider.PostgreSql.Models.Text", b =>
                {
                    b.Navigation("OptionList");
                });
#pragma warning restore 612, 618
        }
    }
}
